### PR TITLE
Code changes from Tanya in init_atmosphere for:

### PR DESCRIPTION
**Pull request by hu5970**
1) RAP vegfra is getting into initial file (init.nc). 2) correction in Vtable for canopy water

The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).

### CODE REVIEW

**Comment by hu5970** [comment]
To use the new code, the following changes needed:

1) new  /mnt/lfs5/BMC/wrfruc/smirnova/Vtable.raphrrr.
2) The namelist change is:
&dimensions
    config_nvertlevels = 59
    config_nsoillevels = 9
    config_nfglevels     = 51
    config_nfgsoillevels = 9
    config_nsoilcat      = 16
    **config_nvegopt       = 2**
/

**Review by tanyasmirnova — APPROVED** [review]
@hu5970 Ming, the changes to the code look good to me. Thank you! Do we need to include Vtable and namelist.init_atmosphere?

**Comment by hu5970** [comment]
@tanyasmirnova Do you know where we can include Vtable and namelist.init_atmosphere?

**Comment by tanyasmirnova** [comment]
@hu5970 Ming, the description of namelist.init_atmosphere is in/mnt/lfs5/BMC/wrfruc/smirnova/MPAS_code/MPAS_gsl_15jul24/src/core_init_atmosphere/inc. It has the default value  config_nvegopt=1. The Vtable.RAP.HRRR should be in the WPS code I think.

**Pull request closed without merging**
